### ISSUE TITLE
[question] BeanTransformer to skip null values

### ISSUE THREAD

**Issue by renannprado** [ExpediaGroup/bull#499]
Hello!

First of all, thanks for the lib!

I have a situation where I have `newBean` and `oldBean`, both are instances of `MyClass`.

Basically what I want to achieve is to copy fields from `newBean` into `oldBean` **only** if they are not null.

```java
newBean.setValue1(null);
newBean.setValue2("something new");
oldBean.setValue1("current value");
oldBean.setValue2("something old");

// copy non-null fields

oldBean.getValue1().equals("current value")
oldBean.getValue2().equals("something new")
```

I thought that maybe having a custom implementation of `BeanTransformer` or extending `TransformerImpl` could do the trick, but I didn't find a way to do it.

Can you give me a hint of how can I do it?

One way of achieving this would be to dynamically create a field list (of null value fields) and put it into `skipTransformationForField`, but I thought maybe there's a smarter way to do that.

Thanks

**Comment by fborriello** [comment]
Hi @renannprado, if I understood it correctly, this feature: https://github.com/ExpediaGroup/bull?tab=readme-ov-file#copy-on-an-existing-instance would solve your issue.
Please, let me know
thanks

**Comment by fborriello** [comment]
maybe this then: https://github.com/ExpediaGroup/bull?tab=readme-ov-file#disable-the-default-value-set-for-primitive-types-in-case-they-are-null

**Comment by renannprado** [comment]
@fborriello neither `setDefaultValueForMissingPrimitiveField` or `setDefaultValueForMissingField` helped unfortunately.

Is there a way to hook into the transformer logic so that I can say `if src.null do not copy`?

**Comment by fborriello** [comment]
Nope

**Comment by renannprado** [comment]
So I guess there's no way to achieve what I need with this lib.

Thanks for the help though!
